package POJOS;
// Generated 25-may-2020 2:38:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BackupCompra generated by hbm2java
 */
public class BackupCompra  implements java.io.Serializable {


     private Integer id;
     private BackupViaje backupViaje;
     private Tarjeta tarjeta;
     private double importe;
     private int pasajeros;
     private String localizador;
     private Date fechaBaja;
     private Set backupOcupacions = new HashSet(0);

    public BackupCompra() {
    }

	
    public BackupCompra(BackupViaje backupViaje, Tarjeta tarjeta, double importe, int pasajeros, String localizador, Date fechaBaja) {
        this.backupViaje = backupViaje;
        this.tarjeta = tarjeta;
        this.importe = importe;
        this.pasajeros = pasajeros;
        this.localizador = localizador;
        this.fechaBaja = fechaBaja;
    }
    public BackupCompra(BackupViaje backupViaje, Tarjeta tarjeta, double importe, int pasajeros, String localizador, Date fechaBaja, Set backupOcupacions) {
       this.backupViaje = backupViaje;
       this.tarjeta = tarjeta;
       this.importe = importe;
       this.pasajeros = pasajeros;
       this.localizador = localizador;
       this.fechaBaja = fechaBaja;
       this.backupOcupacions = backupOcupacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BackupViaje getBackupViaje() {
        return this.backupViaje;
    }
    
    public void setBackupViaje(BackupViaje backupViaje) {
        this.backupViaje = backupViaje;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }
    public int getPasajeros() {
        return this.pasajeros;
    }
    
    public void setPasajeros(int pasajeros) {
        this.pasajeros = pasajeros;
    }
    public String getLocalizador() {
        return this.localizador;
    }
    
    public void setLocalizador(String localizador) {
        this.localizador = localizador;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public Set getBackupOcupacions() {
        return this.backupOcupacions;
    }
    
    public void setBackupOcupacions(Set backupOcupacions) {
        this.backupOcupacions = backupOcupacions;
    }




}


