package POJOS;
// Generated 25-may-2020 2:38:58 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BackupOcupacion generated by hbm2java
 */
public class BackupOcupacion  implements java.io.Serializable {


     private Integer id;
     private BackupCompra backupCompra;
     private BackupViajero backupViajero;
     private int asiento;
     private double importe;
     private Date fechaBaja;

    public BackupOcupacion() {
    }

    public BackupOcupacion(BackupCompra backupCompra, BackupViajero backupViajero, int asiento, double importe, Date fechaBaja) {
       this.backupCompra = backupCompra;
       this.backupViajero = backupViajero;
       this.asiento = asiento;
       this.importe = importe;
       this.fechaBaja = fechaBaja;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public BackupCompra getBackupCompra() {
        return this.backupCompra;
    }
    
    public void setBackupCompra(BackupCompra backupCompra) {
        this.backupCompra = backupCompra;
    }
    public BackupViajero getBackupViajero() {
        return this.backupViajero;
    }
    
    public void setBackupViajero(BackupViajero backupViajero) {
        this.backupViajero = backupViajero;
    }
    public int getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(int asiento) {
        this.asiento = asiento;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }




}


