package POJOS;
// Generated 25-may-2020 2:38:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BackupViaje generated by hbm2java
 */
public class BackupViaje  implements java.io.Serializable {


     private Integer id;
     private Horario horario;
     private Date fecha;
     private int plazas;
     private Date fechaBaja;
     private Set backupCompras = new HashSet(0);

    public BackupViaje() {
    }

	
    public BackupViaje(Horario horario, Date fecha, int plazas, Date fechaBaja) {
        this.horario = horario;
        this.fecha = fecha;
        this.plazas = plazas;
        this.fechaBaja = fechaBaja;
    }
    public BackupViaje(Horario horario, Date fecha, int plazas, Date fechaBaja, Set backupCompras) {
       this.horario = horario;
       this.fecha = fecha;
       this.plazas = plazas;
       this.fechaBaja = fechaBaja;
       this.backupCompras = backupCompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getPlazas() {
        return this.plazas;
    }
    
    public void setPlazas(int plazas) {
        this.plazas = plazas;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public Set getBackupCompras() {
        return this.backupCompras;
    }
    
    public void setBackupCompras(Set backupCompras) {
        this.backupCompras = backupCompras;
    }




}


