package POJOS;
// Generated 25-may-2020 2:38:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer id;
     private Tarjeta tarjeta;
     private Viaje viaje;
     private Date fecha;
     private double importe;
     private int pasajeros;
     private String localizador;
     private Set ocupacions = new HashSet(0);

    public Compra() {
    }

	
    public Compra(Tarjeta tarjeta, Viaje viaje, Date fecha, double importe, int pasajeros, String localizador) {
        this.tarjeta = tarjeta;
        this.viaje = viaje;
        this.fecha = fecha;
        this.importe = importe;
        this.pasajeros = pasajeros;
        this.localizador = localizador;
    }
    public Compra(Tarjeta tarjeta, Viaje viaje, Date fecha, double importe, int pasajeros, String localizador, Set ocupacions) {
       this.tarjeta = tarjeta;
       this.viaje = viaje;
       this.fecha = fecha;
       this.importe = importe;
       this.pasajeros = pasajeros;
       this.localizador = localizador;
       this.ocupacions = ocupacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getImporte() {
        return this.importe;
    }
    
    public void setImporte(double importe) {
        this.importe = importe;
    }
    public int getPasajeros() {
        return this.pasajeros;
    }
    
    public void setPasajeros(int pasajeros) {
        this.pasajeros = pasajeros;
    }
    public String getLocalizador() {
        return this.localizador;
    }
    
    public void setLocalizador(String localizador) {
        this.localizador = localizador;
    }
    public Set getOcupacions() {
        return this.ocupacions;
    }
    
    public void setOcupacions(Set ocupacions) {
        this.ocupacions = ocupacions;
    }




}


