package POJOS;
// Generated 25-may-2020 2:38:58 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private Integer id;
     private Horario horario;
     private Date fecha;
     private int plazasTotales;
     private int plazasDisponibles;
     private Set compras = new HashSet(0);

    public Viaje() {
    }

	
    public Viaje(Horario horario, Date fecha, int plazasTotales, int plazasDisponibles) {
        this.horario = horario;
        this.fecha = fecha;
        this.plazasTotales = plazasTotales;
        this.plazasDisponibles = plazasDisponibles;
    }
    public Viaje(Horario horario, Date fecha, int plazasTotales, int plazasDisponibles, Set compras) {
       this.horario = horario;
       this.fecha = fecha;
       this.plazasTotales = plazasTotales;
       this.plazasDisponibles = plazasDisponibles;
       this.compras = compras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getPlazasTotales() {
        return this.plazasTotales;
    }
    
    public void setPlazasTotales(int plazasTotales) {
        this.plazasTotales = plazasTotales;
    }
    public int getPlazasDisponibles() {
        return this.plazasDisponibles;
    }
    
    public void setPlazasDisponibles(int plazasDisponibles) {
        this.plazasDisponibles = plazasDisponibles;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


